# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52370cfcd6b6e9e107996e85555a73c8ff9bccbdc483fd75808a06585543590cc7e2893950346702f7da974d2f9a6065ffde9b0f2c1c9f8ac1c7564373f29115

test:
  secret_key_base: 3fc79fd034be4ab52d5a5b84f732d8e04d227277cc6baadd35448cb04121f49f6b08a15bc4c0009551f3f1b9046745237596d0b27c5ae0a61caa757a007cf900

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
